[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nickname_registry = "9hbJLs2EGPdvVLcxQs2N2QqZUhh8r2J86PK8rYBRxJdt"
prophet_games = "G1xjFqQ976m5xsybUCjLxjJxRCcx3PCwpxBgj7VM6ME7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
